# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_load_save.py
    deps:
    - src/stage_01_load_save.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - artifacts/raw_local_dir/data.csv