# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_load_save.py
    deps:
    - src/stage_01_load_save.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py
    deps:
    - src/stage_02_split_data.py
    - src/utils/common.py
    - artifacts/raw_local_dir/data.csv
    - configs/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
    - artifacts/split_data_dir/train.csv
    - artifacts/split_data_dir/test.csv